In [2]:
import numpy as np

In [3]:
# [1,2,0,0,4,0]

In [4]:
a = np.array([1,2,0,0,4,0])

In [5]:
a

array([1, 2, 0, 0, 4, 0])

In [6]:
np.where(a==0)

(array([2, 3, 5], dtype=int64),)

In [7]:
# nz = np.nonzero([1,2,0,0,4,0])
# print(nz)

In [8]:
np.nonzero(a)

(array([0, 1, 4], dtype=int64),)

In [9]:
np.where(a!=0)

(array([0, 1, 4], dtype=int64),)