In [1]:
import numpy as np

In [2]:
#  np.random.randint(1, 5, size=(4, 4))


In [3]:
# k = np.random.random ([3,4]) * 10

In [4]:
# a = np.random.randint(100, size = (5,4)) #a is a variable(object)

In [5]:
a = np.random.randint(1,101,size=(3,3,3))

In [6]:
a

array([[[14, 96, 42],
        [89, 88, 59],
        [24, 90, 79]],

       [[38, 11, 61],
        [32, 78, 46],
        [20, 84,  2]],

       [[99, 35, 13],
        [21, 35, 86],
        [ 7, 60, 22]]])

In [7]:
b = np.random.random([3,3,3])

In [8]:
b

array([[[0.66566919, 0.09437173, 0.60399775],
        [0.2713962 , 0.53753892, 0.04655046],
        [0.7663666 , 0.89281214, 0.79562024]],

       [[0.03081439, 0.14778461, 0.9086698 ],
        [0.72685425, 0.68005663, 0.65127984],
        [0.29629602, 0.75178899, 0.75061824]],

       [[0.16109025, 0.00821971, 0.42226534],
        [0.81464253, 0.8795457 , 0.12571061],
        [0.2513646 , 0.76638261, 0.32606296]]])

In [9]:
c = np.random.random([3,3,3])*100

In [10]:
c

array([[[ 1.64922894, 96.3476462 , 59.32497336],
        [28.80904716,  5.94080593, 64.78283699],
        [67.65099167,  6.63906912, 14.01806495]],

       [[64.40322528,  1.31505326, 65.89650694],
        [55.05428878, 72.77331365, 89.19799766],
        [95.78851958, 15.61385867, 51.38464213]],

       [[32.69845297, 70.57593522, 15.56367784],
        [17.95062948, 84.22616762, 54.84167006],
        [37.08300643, 28.22607611, 94.9963614 ]]])

In [11]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.98915893 0.46366601 0.48204046]
  [0.21510208 0.34929689 0.00362694]
  [0.89808815 0.42353574 0.87592221]]

 [[0.03443127 0.73744763 0.521069  ]
  [0.54191736 0.62299667 0.1920632 ]
  [0.81194727 0.75204609 0.85730947]]

 [[0.17035999 0.01027282 0.83953385]
  [0.04211441 0.83708015 0.77408095]
  [0.64929229 0.71946413 0.67451666]]]
