In [2]:
import numpy as np

In [ ]:
#  np.random.randint(1, 5, size=(4, 4))


In [ ]:
# k = np.random.random ([3,4]) * 10

In [ ]:
# a = np.random.randint(100, size = (5,4)) #a is a variable(object)

In [3]:
a = np.random.randint(1,101,size=(3,3,3))

In [4]:
a

array([[[ 24,  72,  98],
        [ 67,   3,   7],
        [ 94,  36,  24]],

       [[ 77,  23, 100],
        [ 14,  26,  83],
        [ 33,  14,  84]],

       [[ 90,  77,  17],
        [ 10,  15,  16],
        [ 71,  11,  87]]])

In [7]:
b = np.random.random([3,3,3])

In [8]:
b

array([[[0.2099961 , 0.96951166, 0.57605822],
        [0.87384377, 0.2943517 , 0.10149685],
        [0.11101777, 0.27791435, 0.85511862]],

       [[0.93382173, 0.20715069, 0.57060796],
        [0.53736813, 0.79342063, 0.15933061],
        [0.07881107, 0.86379365, 0.62298666]],

       [[0.31271475, 0.71800868, 0.42482516],
        [0.81328996, 0.60133904, 0.481886  ],
        [0.4250658 , 0.46810993, 0.73174101]]])

In [9]:
c = np.random.random([3,3,3])*100

In [10]:
c

array([[[39.69981319, 97.09841151, 57.69987941],
        [80.19889726, 76.74657697, 62.18408582],
        [14.12338794, 32.49630217, 60.69212574]],

       [[14.13509936, 50.80110785, 75.46294125],
        [ 8.58657581, 33.45606207, 80.01161204],
        [94.9507764 , 42.81537763, 44.98699366]],

       [[24.20880389, 56.90653658, 98.69628216],
        [ 0.91840965, 92.54417898, 68.96916751],
        [44.96895145, 93.52168748,  9.33332493]]])