In [41]:
import numpy as np

In [42]:
a = np.zeros([7,9])
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [43]:
size_hight = a.shape[0]
size_wide = a.shape[1]

    

In [44]:
for i  in range(size_hight):
    for y in range(size_wide):
        if i == 0 or i == size_hight-1:
            a[i,y] = 1
        elif y == 0 or y == size_wide-1:
        a[i,y] = 1
        # print("{item}\n".format(item=a[i,y]))
print(a)

IndentationError: expected an indented block after 'elif' statement on line 5 (1602102111.py, line 6)

In [ ]:
def border_array(height, wide):
    a = np.zeros([height,wide])
    size_hight = a.shape[0]
    size_wide = a.shape[1]
    for i  in range(size_hight):
        for y in range(size_wide):
            if i == 0 or i == size_hight-1:
                a[i,y] = 1
            elif y == 0 or y == size_wide-1:
                a[i,y] = 1
        # print("{item}\n".format(item=a[i,y]))
    print(a)

In [ ]:
border_array(5,8)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
