In [23]:
import numpy as np

In [24]:
a = np.random.randint(1,101, size=[10,10])
print(a)

[[  8  56  37  32   3  20  32  21  49  26]
 [ 45  86  29  28  25  26  75  59  98  93]
 [ 40   5  79  93  34  53  26  34  54  71]
 [ 54  61  58  63  32  76  71  39  67  74]
 [ 99  28  47  42  65  98  13  33  10  79]
 [ 59  83  98  47   6  37  97  67  58  94]
 [ 22  67  80  19  51  68  83  49  97  63]
 [ 47  55  98  83   7  11  19  81   5  17]
 [ 62  39  27   4  36  26  43  50  66  10]
 [ 33 100  16  83  50  97  62  94  90  75]]


In [25]:
a.mean()

51.77

In [26]:

def border_ones(arr2d):
    # a = np.zeros([height,wide])
    size_hight = arr2d.shape[0]
    size_wide = arr2d.shape[1]
    for i  in range(size_hight):
        for y in range(size_wide):
            if i == 0 or i == size_hight-1:
                arr2d[i,y] = 1
            elif y == 0 or y == size_wide-1:
                arr2d[i,y] = 1
        # print("{item}\n".format(item=a[i,y]))
    print(arr2d)

In [27]:
border_ones(a)

[[ 1  1  1  1  1  1  1  1  1  1]
 [ 1 86 29 28 25 26 75 59 98  1]
 [ 1  5 79 93 34 53 26 34 54  1]
 [ 1 61 58 63 32 76 71 39 67  1]
 [ 1 28 47 42 65 98 13 33 10  1]
 [ 1 83 98 47  6 37 97 67 58  1]
 [ 1 67 80 19 51 68 83 49 97  1]
 [ 1 55 98 83  7 11 19 81  5  1]
 [ 1 39 27  4 36 26 43 50 66  1]
 [ 1  1  1  1  1  1  1  1  1  1]]


In [28]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [30]:
Z = np.ones((10,10))
Z = np.pad(Z, pad_width=3, mode='constant', constant_values=5)
print(Z)

[[5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 5. 5. 5.]
 [5. 5. 5. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 5. 5. 5.]
 [5. 5. 5. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 5. 5. 5.]
 [5. 5. 5. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 5. 5. 5.]
 [5. 5. 5. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 5. 5. 5.]
 [5. 5. 5. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 5. 5. 5.]
 [5. 5. 5. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 5. 5. 5.]
 [5. 5. 5. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 5. 5. 5.]
 [5. 5. 5. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 5. 5. 5.]
 [5. 5. 5. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]


In [31]:
Z = np.ones((9,9))

In [32]:
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [33]:
Z[[0, -1], :] = 0
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [34]:
# Using fancy indexing
Z[:, [0, -1]] = 0
# Z[[0, -1], :] = 0
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
