In [74]:
import numpy as np

In [75]:
b = np.random.randint(1,11, size=[5,5])

In [76]:
b

array([[ 4, 10,  7,  6,  9],
       [10, 10,  9,  3, 10],
       [ 6,  3,  6,  8,  3],
       [10,  7,  5,  5,  4],
       [ 7,  7,  5,  1,  8]])

In [77]:
for i in range(b.shape[0]):
    for j in range(b.shape[1]):
        if i > j:
            # We are below the diagonal
            b[i,j] = np.random.randint(1,5)
        else:
            continue
b

array([[ 4, 10,  7,  6,  9],
       [ 1, 10,  9,  3, 10],
       [ 1,  1,  6,  8,  3],
       [ 4,  1,  3,  5,  4],
       [ 2,  4,  2,  3,  8]])

In [78]:
# a = np.arange(9).reshape(3, 3)

# a
# array([[0, 1, 2],
#        [3, 4, 5],
#        [6, 7, 8]])

# np.fliplr(a).diagonal()  # Horizontal flip
# array([2, 4, 6])

# np.flipud(a).diagonal()  # Vertical flip
# array([6, 4, 2])

In [79]:
# a = np.arange(9).reshape(3, 3)

# a


In [80]:
# diag_a = np.diagonal(a)
# diag_a

In [81]:
# a_diag_2 = np.fliplr(a).diagonal()
# a_diag_2

In [82]:
# import numpy as np
# arr = np.array([[1,2,3], [4, 5, 6], [7, 8, 9]])

# for i in range(arr.shape[0]):
#     for j in range(arr.shape[1]):
#         if i == j:
#             # We are on a diagonal, do nothing
#             continue
#         else:
#             arr[i,j] = 0

# If you want to only set the "upper" triangle to zero, you would use this instead:

# import numpy as np
# arr = np.array([[1,2,3], [4, 5, 6], [7, 8, 9]])

# for i in range(arr.shape[0]):
#     for j in range(arr.shape[1]):
#         if i > j:
#             # We are above the diagonal
#             arr[i,j] = 0
#         else:
#             continue

# And lastly, if you only want to set the lower diagonal to zero:

# import numpy as np
# arr = np.array([[1,2,3], [4, 5, 6], [7, 8, 9]])

# for i in range(arr.shape[0]):
#     for j in range(arr.shape[1]):
#         if i < j:
#             # We are below the diagonal
#             arr[i,j] = 0
#         else:
#             continue



In [83]:
# import numpy as np
# arr = np.array([[1,2,3], [4, 5, 6], [7, 8, 9]])

# for i in range(arr.shape[0]):
#     for j in range(arr.shape[1]):
#         if i == j:
#             # We are on a diagonal, do nothing
#             continue
#         else:
#             arr[i,j] = 0

# arr

In [84]:
# import numpy as np
# arr = np.array([[1,2,3], [4, 5, 6], [7, 8, 9]])

# for i in range(arr.shape[0]):
#     for j in range(arr.shape[1]):
#         if i > j:
#             # We are below the diagonal
#             arr[i,j] = np.random.randint(1,5)
#         else:
#             continue
# arr