In [17]:
import numpy as np

In [18]:
l = 'b'*64
l

'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb'

In [19]:
a=np.array([ list(word) for word in l ]).reshape(8,8)
a

array([['b', 'b', 'b', 'b', 'b', 'b', 'b', 'b'],
       ['b', 'b', 'b', 'b', 'b', 'b', 'b', 'b'],
       ['b', 'b', 'b', 'b', 'b', 'b', 'b', 'b'],
       ['b', 'b', 'b', 'b', 'b', 'b', 'b', 'b'],
       ['b', 'b', 'b', 'b', 'b', 'b', 'b', 'b'],
       ['b', 'b', 'b', 'b', 'b', 'b', 'b', 'b'],
       ['b', 'b', 'b', 'b', 'b', 'b', 'b', 'b'],
       ['b', 'b', 'b', 'b', 'b', 'b', 'b', 'b']], dtype='<U1')

In [20]:
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        if i%2 == 0 and j%2 == 0:
            # We are below the diagonal
            a[i,j] = 'w'
        else:
            continue
a

array([['w', 'b', 'w', 'b', 'w', 'b', 'w', 'b'],
       ['b', 'b', 'b', 'b', 'b', 'b', 'b', 'b'],
       ['w', 'b', 'w', 'b', 'w', 'b', 'w', 'b'],
       ['b', 'b', 'b', 'b', 'b', 'b', 'b', 'b'],
       ['w', 'b', 'w', 'b', 'w', 'b', 'w', 'b'],
       ['b', 'b', 'b', 'b', 'b', 'b', 'b', 'b'],
       ['w', 'b', 'w', 'b', 'w', 'b', 'w', 'b'],
       ['b', 'b', 'b', 'b', 'b', 'b', 'b', 'b']], dtype='<U1')

In [ ]:
# teachers solution
# Z = np.diag(1+np.arange(4),k=-1)
# print(Z)

In [21]:
z = np.diag(1+np.arange(4),k=-1)
z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [22]:
import numpy as np
a = np.arange(12).reshape((4,3))
np.diag(a, k=1)


array([1, 5])

In [26]:
np.arange(4)

array([0, 1, 2, 3])

In [31]:
np.full(8,2)

array([2, 2, 2, 2, 2, 2, 2, 2])

In [32]:
np.full(10,0)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [34]:
np.full(12,1)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [28]:
np.diag(np.full(7,-2))  

array([[-2,  0,  0,  0,  0,  0,  0],
       [ 0, -2,  0,  0,  0,  0,  0],
       [ 0,  0, -2,  0,  0,  0,  0],
       [ 0,  0,  0, -2,  0,  0,  0],
       [ 0,  0,  0,  0, -2,  0,  0],
       [ 0,  0,  0,  0,  0, -2,  0],
       [ 0,  0,  0,  0,  0,  0, -2]])

In [36]:
np.full([3,5],7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])