In [1]:
import numpy as np

In [ ]:
# a = np.array([0, 1, 2])

# np.tile(a, 2)
# array([0, 1, 2, 0, 1, 2])

# np.tile(a, (2, 2))
# array([[0, 1, 2, 0, 1, 2],
#        [0, 1, 2, 0, 1, 2]])

# np.tile(a, (2, 1, 2))
# array([[[0, 1, 2, 0, 1, 2]],
#        [[0, 1, 2, 0, 1, 2]]])

In [10]:
a = np.array([0, 1])
a

array([0, 1])

In [13]:
np.tile(a, (8,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [ ]:
# b = np.array([[1, 2], [3, 4]])

# np.tile(b, 2)
# array([[1, 2, 1, 2],
#        [3, 4, 3, 4]])

# np.tile(b, (2, 1))
# array([[1, 2],
#        [3, 4],
#        [1, 2],
#        [3, 4]])

In [14]:
b = np.array([[0, 1],[1,0]])
b

array([[0, 1],
       [1, 0]])

In [18]:
np.tile(b, (4,4))


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [19]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
