In [1]:
# 22. Normalize a 5x5 random matrix (★☆☆)

import numpy as np


In [7]:
a = np.random.rand(5,5)

In [8]:
a

array([[0.20212215, 0.59229377, 0.17264362, 0.18491405, 0.99823544],
       [0.37721619, 0.20725037, 0.93944035, 0.49500975, 0.18394537],
       [0.74658891, 0.28432468, 0.94872337, 0.90459187, 0.92554885],
       [0.48570343, 0.15822283, 0.24525323, 0.22782233, 0.16578653],
       [0.28206453, 0.99483171, 0.84625199, 0.03768369, 0.69409499]])

In [10]:
df= np.random.random((5,5))
print("Original Array:")
print(df)

Original Array:
[[0.34802937 0.38379536 0.27897188 0.14187634 0.86984994]
 [0.17562563 0.96591548 0.61076247 0.12615624 0.53298635]
 [0.57308958 0.91947268 0.59361382 0.87377734 0.30965073]
 [0.13597463 0.33122856 0.88032206 0.75003953 0.74605815]
 [0.07252037 0.36393104 0.12150848 0.41420758 0.59309556]]


In [11]:
dfmax, dfmin = df.max(), df.min()
df = (df - dfmin)/(dfmax - dfmin)
print(df)

[[0.30838428 0.34841806 0.23108646 0.07763191 0.89247139]
 [0.11540835 1.         0.60246815 0.06003601 0.51541135]
 [0.56029993 0.94801538 0.58327322 0.89686742 0.26542608]
 [0.07102598 0.2895787  0.9041931  0.75836453 0.75390807]
 [0.         0.32618342 0.05483365 0.38245924 0.58269313]]


In [12]:
print("After normalization:")
print(df)

After normalization:
[[0.30838428 0.34841806 0.23108646 0.07763191 0.89247139]
 [0.11540835 1.         0.60246815 0.06003601 0.51541135]
 [0.56029993 0.94801538 0.58327322 0.89686742 0.26542608]
 [0.07102598 0.2895787  0.9041931  0.75836453 0.75390807]
 [0.         0.32618342 0.05483365 0.38245924 0.58269313]]


In [14]:
z = np.arange(11,100,3)
z

array([11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53, 56, 59,
       62, 65, 68, 71, 74, 77, 80, 83, 86, 89, 92, 95, 98])

In [20]:
x = np.full([5,5],np.random.randint(100))
x

array([[39, 39, 39, 39, 39],
       [39, 39, 39, 39, 39],
       [39, 39, 39, 39, 39],
       [39, 39, 39, 39, 39],
       [39, 39, 39, 39, 39]])

In [22]:
np.random.randint(1,25, size=[5,5])

array([[16, 15, 13, 20, 15],
       [11, 21,  1, 13, 13],
       [22, 22, 12, 16, 19],
       [16, 11,  7, 11,  5],
       [16, 11,  5, 17, 17]])