In [3]:
# 22. Normalize a 5x5 random matrix (★☆☆)

import numpy as np


In [4]:
a = np.random.rand(5,5)

In [5]:
a

array([[0.14408066, 0.24202652, 0.70344471, 0.17948261, 0.54801174],
       [0.00268988, 0.10734143, 0.40103337, 0.57852179, 0.20051409],
       [0.72599757, 0.0650743 , 0.69879694, 0.29025535, 0.19605385],
       [0.00996741, 0.81791373, 0.55694844, 0.4282865 , 0.49083734],
       [0.18262085, 0.46493498, 0.21677421, 0.27415659, 0.72586022]])

In [6]:
df= np.random.random((5,5))
print("Original Array:")
print(df)

Original Array:
[[0.10787294 0.20866614 0.20208288 0.00220369 0.44084783]
 [0.26171205 0.98453321 0.59498871 0.3038253  0.95680008]
 [0.62751661 0.66888325 0.91432535 0.96501963 0.34446256]
 [0.56271772 0.74747442 0.40171676 0.31103329 0.55406784]
 [0.28042643 0.07829154 0.05581355 0.64307864 0.89248533]]


In [7]:
dfmax, dfmin = df.max(), df.min()
df = (df - dfmin)/(dfmax - dfmin)
print(df)

[[0.10757006 0.21017637 0.20347469 0.         0.44653462]
 [0.26417648 1.         0.60344824 0.30704729 0.97176799]
 [0.63656126 0.67867202 0.92852921 0.98013541 0.34841554]
 [0.57059675 0.75867691 0.40669965 0.31438493 0.56179127]
 [0.28322751 0.07745654 0.05457422 0.65240322 0.90629633]]


In [8]:
print("After normalization:")
print(df)

After normalization:
[[0.10757006 0.21017637 0.20347469 0.         0.44653462]
 [0.26417648 1.         0.60344824 0.30704729 0.97176799]
 [0.63656126 0.67867202 0.92852921 0.98013541 0.34841554]
 [0.57059675 0.75867691 0.40669965 0.31438493 0.56179127]
 [0.28322751 0.07745654 0.05457422 0.65240322 0.90629633]]


In [9]:
z = np.arange(11,100,3)
z

array([11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53, 56, 59,
       62, 65, 68, 71, 74, 77, 80, 83, 86, 89, 92, 95, 98])

In [10]:
x = np.full([5,5],np.random.randint(100))
x

array([[98, 98, 98, 98, 98],
       [98, 98, 98, 98, 98],
       [98, 98, 98, 98, 98],
       [98, 98, 98, 98, 98],
       [98, 98, 98, 98, 98]])

In [11]:
np.random.randint(1,25, size=[5,5])

array([[20,  3, 14,  3,  7],
       [ 2, 23, 15,  7,  2],
       [18,  4, 18,  1, 10],
       [18,  9,  3,  9, 20],
       [10,  7, 24,  8,  3]])

### teachers solution

In [13]:
# `hint: (x -mean)/std`

# ```python
Zb = np.random.random((5,5))
Z = (Zb - np.mean (Zb)) / (np.std (Zb))
print(Z)

[[ 1.0918364   0.90434027 -0.84772933  0.00528593 -0.40921308]
 [ 1.4746546   0.02012103  1.68787137 -1.25346271 -0.16663766]
 [-1.24213878  0.53625118  1.7834619   1.33288171 -0.12216014]
 [-0.43004438 -0.8595306  -1.53320174  1.01153787 -0.69520642]
 [-1.47045826 -0.96139092  0.05399519 -0.58957394  0.67851051]]


In [14]:
print(Zb)

[[0.80761377 0.75619465 0.2757054  0.50963712 0.39596451]
 [0.9125982  0.51370551 0.97107097 0.16443668 0.46248863]
 [0.16754217 0.65524954 0.99728581 0.87371827 0.47468619]
 [0.39025172 0.272469   0.08772078 0.78559262 0.31753343]
 [0.10492761 0.24453473 0.52299519 0.34650218 0.69426288]]


In [15]:
np.std (Zb)

0.27424096357814176

In [16]:
np.mean (Zb)

0.5081875029757726