In [1]:
import numpy as np
from sys import getsizeof

In [2]:
y = np.zeros(10)

In [3]:
# >>> import numpy as np
# >>> from sys import getsizeof
# >>> a = [0] * 1024
# >>> b = np.array(a)
# >>> getsizeof(a)
# 8264
# >>> b.nbytes
# 8192


In [4]:
a = [0] * 1024
type(a)


list

In [5]:
b =np.array(a)

In [6]:
len(a)

1024

In [7]:
y.nbytes

80

In [8]:
b.nbytes

4096

In [ ]:
# Z = np.zeros((10,10))
# print("%d bytes" % (Z.size * Z.itemsize))

In [9]:
z = np.zeros((10,10))
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [10]:
z.nbytes

800

In [11]:
print(z.size)

100


In [12]:
print(z.itemsize)

8


In [14]:
print("%d bytes" % (z.size * z.itemsize))

800 bytes


In [15]:
getsizeof(z)

928