In [2]:
import numpy as np

In [3]:
n_arr =np.arange(0,11)
print(n_arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [4]:
np.flip(n_arr)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [5]:
n_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.flipud(n_arr)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [7]:
n_arr[::-1]


array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])